### ISSUE TITLE
ASP Core 6 LTS

### ISSUE THREAD

**Issue by yankdoodle** [syncfusion/ej2-showcase-aspnetmvc-outlook#12]
Hello, this is very old can you **please update to ASP core 6** with Identity, SF controls. 

Also is it possible to let user switch to compact view
Show SF controls with email templates

**Comment by kmuthukumarmkm** [comment]
@yankdoodle - We have prepared an outlook sample in ASP.NET core with .NET6 version which you can download from the link below

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/Outlook_Core_Net62051097623

Also, we would like to inform you that, currently, we don’t have any out-look templates inbuilt with our controls. Please refer to the below link for creating an out-look style using Syncfusion controls

https://ej2.syncfusion.com/aspnetcore/Splitter/OutlookStyleLayout#/fluent

Thanks.

**Comment by rajendranr-5483** [comment]
Hi All,

This issue has not had any activity for a long time. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.

Regards,
Rajendran R
